# Generated by Django 4.2 on 2023-04-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicaciones', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
    ]
