# Generated by Django 4.2 on 2023-04-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicaciones', '0004_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='comentarios',
            field=models.CharField(max_length=500),
        ),
    ]
